### ISSUE TITLE
Socket.io connection path does not follow Documentation

### ISSUE THREAD

**Issue by perki** [pryv/open-pryv.io#1]
We noticed that to initialize a socket.io connection, Open pryv.io accept the following format: 

```
https://{hostname}/{username}?auth={token}&resource={username}
```

Instead of 

```
https://{hostname}/{username}/{username}?auth={token}&resource={username}
```

as per the documentation

Pryv's team is working on a fix..

**Comment by kebetsi** [comment]
Fixed by [1.5.18](https://github.com/pryv/open-pryv.io/tree/1.5.18).
