### ISSUE TITLE
Incorrect status code for existing items

### ISSUE THREAD

**Issue by gczene** [pryv/open-pryv.io#10]
Hi there

In the case of POSTing an existing item (e.g. register a user) the server response `400`. It seems to be incorrect since [by MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400):
```
...to be a client error (e.g., malformed request syntax, 
invalid request message framing, or deceptive request routing).
```
In this scenario, the request is formed properly so definitely not a bad request. `409 conflict` maybe?

happens here:
https://github.com/pryv/open-pryv.io/blob/6c738464da5be421206663ebe25b2eeb08f88dd6/components/errors/src/factory.js#L148

Thanks,

**Comment by kebetsi** [comment]
Hi Gabor,

We've changed the already existing errors to a 409 HTTP status. Thanks for notifying us this discrepancy.
