### ISSUE TITLE
Partially missing error explanation in user registration response

### ISSUE THREAD

**Issue by gczene** [pryv/open-pryv.io#11]
When both username and email are registered, the email member is missing from the error explanation, only the username problem described.

# Scenarios:

### if only the username reserved, the response is:
```
{
   "error":{
      "id":"item-already-exists",
      "message":"An user with username 'gabortest001' already exists",
      "data":{
         "username":"gabortest001"
      }
   },
   "meta":{
      "apiVersion":"1.6.2-2-open",
      "serverTime":1607330501.756,
      "serial":"t1607325000"
   }
}
```
### if the email only: 
```
{
   "error":{
      "id":"item-already-exists",
      "message":"An user with email \"czene.gabor22@gmail.com\" already exists",
      "data":{
         "email":"czene.gabor22@gmail.com"
      }
   },
   "meta":{
      "apiVersion":"1.6.2-2-open",
      "serverTime":1607330390.87,
      "serial":"t1607325000"
   }
}
```
### if both are registered

```
{
   "error":{
      "id":"item-already-exists",
      "message":"An user with username \"gabortest001\" already exists",
      "data":{
         "username":"gabortest001"
      }
   },
   "meta":{
      "apiVersion":"1.6.2-2-open",
      "serverTime":1607331212.625,
      "serial":"t1607325000"
   }
}
```

Probably it designed this way but because the `data` property holds an object it may contain the email too, to indicate to all problems for the frontend. 

What I expected in the data member (regardless of the message):
```
{
   "error":{
      "id":"item-already-exists",
      "message":"An user with username 'gabortest001' already exists",
      "data":{
         "username":"gabortest001",
         "email": "something@blah.com"
      }
   },
   "meta":{
      "apiVersion":"1.6.2-2-open",
      "serverTime":1607330501.756,
      "serial":"t1607325000"
   }
}
```

**Comment by kebetsi** [comment]
Thanks for notifying us @gczene. We'll add additional conflicting keys to user creation in a future release.

**Comment by gczene** [comment]
thank you! Looking forward to that!

**Comment by kebetsi** [comment]
Hi @gczene,

We will unfortunately not implement this feature now as the underlying MongoDB transaction does throw upon the first encountered error, not providing the full list of conflicting keys.
Please let us know if this feature is important to you so we can consider it as it is in our next roadmap.

Best Regards,
