### ISSUE TITLE
Cannot login with created user's credentials

### ISSUE THREAD

**Issue by emilt27** [pryv/open-pryv.io#12]
I've run open-pryv.io locally via docker. I've even registered a new user, but I cannot log in with this user:
![image](https://user-images.githubusercontent.com/22050249/114308047-27c2c500-9aeb-11eb-917a-27bffa773526.png)
What did I miss?
Here are logs:
![image](https://user-images.githubusercontent.com/22050249/114308110-5d67ae00-9aeb-11eb-9c4a-6a113375b8e5.png)

**Comment by kebetsi** [comment]
Hi @emilt27,

We've fixed an issue that was present with this release (https://github.com/pryv/open-pryv.io/commit/8eba6fdd78043529b12c15055aaa8273340837ee)

You might have to pull the new containers using: `docker-compose -f $FILE pull`

Please let us know if this fixes your issue.

**Comment by emilt27** [comment]
@kebetsi yep it works now, thanks
