### ISSUE TITLE
Ability to use Pryv in tests

### ISSUE THREAD

**Issue by emilt27** [pryv/open-pryv.io#14]
I'd like to use Pryv in kind of integration tests and therefore I need somehow to run each test in isolated scope, e.g under a transaction that I can start before and rollback after each test, or just an API endpoint that I can use to erase all data safely. Is it possible right now? Right now I see the following way only:

Connect to mongo DB directly and remove all collections via:
```
mongo [database] --eval "db.getCollectionNames().forEach(function(n){db[n].remove()});"
```

What would you recommend?

**Comment by perki** [comment]
Hello emit27, 

In our tests suite we do apply a method similar than the one you suggest of "cleaning" mongodb.
You might want to create a random user each time you run your tests and cleanup every items related to this user at the end. 

If you don't need data between tests, you can simply erase mongodb data folder and restart it for each test run.

**Comment by emilt27** [comment]
OK, if it should not produce any issues then I will use mongodb clean up.
