### ISSUE TITLE
Docker version certificates expired

### ISSUE THREAD

**Issue by ovesco** [pryv/open-pryv.io#15]
The rec.la certificates are expired in the Docker download link, as well as in the [rec.la repo](https://github.com/pryv/rec-la).
Do you have any mean of updating them? Or do you plan to publish some new ones?

**Comment by perki** [comment]
Hello Guillaume, 
Indeed thanks for notifying us. 
We just updated the certificates.
Best regards, 
Pierre-Mikael

**Comment by ovesco** [comment]
Perfect thanks

**Comment by ovesco** [comment]
Hey, sorry to bring this back up but certificates are expired again

**Comment by perki** [comment]
Hello Guillaume,
Thanks for the notification, we look into this and keep you posted. 
Best regards, 
Pierre-Mikael

**Comment by perki** [comment]
Hello Guillaume, 
Actually the simplest way to update the rec.la certificate is to download them from https://www.rec.la they are kept up to date automatically. 
You just need to place the two following files in the `rec.la-certificates` directory 
- `https://www.rec.la/rec.la-bundle.crt`
- `https://www.rec.la/rec.la-key.pem`

Best regards, 
Pierre-Mikael

**Comment by perki** [comment]
Hello Guillaume, 
The latest 1.9.0 release of Open-pryv.io includes a self-refresh of rec.la certificates.
Kind regards, 
Pierre-Mikael
