### ISSUE TITLE
Error on connection page

### ISSUE THREAD

**Issue by medval** [pryv/open-pryv.io#2]
Hello everybody!
Thanks for the open source initiative!

We tried to install Open Pryv on docker to test the plateform. Unfortunately we have a problem when we try to access the login page at http://pryv-address/www/assets/access
The form is displayed and it is possible to create an account. But when we click on "Login" we have an error.
The console says: 
```
TypeError: "t.accessState is undefined"
    e AccessStates.js:7
    w runtime.js:62
    _invoke runtime.js:296
    e runtime.js:114
    i asyncToGenerator.js:17
    default asyncToGenerator.js:35
    e _export.js:36
    default asyncToGenerator.js:14
    H login.js:9
    s controller.js:21
    w runtime.js:62
    _invoke runtime.js:296
    e runtime.js:114
    i asyncToGenerator.js:17
    default asyncToGenerator.js:35
    e _export.js:36
    default asyncToGenerator.js:14
    e Authorization.vue:129
    w runtime.js:62
    _invoke runtime.js:296
    e runtime.js:114
    i asyncToGenerator.js:17
    default asyncToGenerator.js:35
    e _export.js:36
    default asyncToGenerator.js:14
    submit Authorization.vue:124
    VueJS 4
    click vuetify.js:1391
    VueJS 3
AppError.js:37:12
    value AppError.js:37
    e AppError.js:33
    s controller.js:26
    w runtime.js:62
    _invoke runtime.js:296
    e runtime.js:114
    i asyncToGenerator.js:17
    i asyncToGenerator.js:30
```

Thank you in advance for any tip

**Comment by anastasia-bzd** [comment]
It looks like a configuration problem. 
Do you mind posting your question on the dedicated page here : https://support.pryv.com/hc/en-us/community/topics/360000740160-Configuration-and-setup ?
We will address it directly there.

Thank you very much !

**Comment by perki** [comment]
The thread has ben continued on: https://support.pryv.com/hc/en-us/community/posts/360008919100-Error-on-connection-page-
