### ISSUE TITLE
open-pryv.io / Docker / Windows

### ISSUE THREAD

**Issue by chewieplus** [pryv/open-pryv.io#3]
Hello all,

I am trying to dockerize an open-pryv.io to be able to deploy it on Windows machines (and Openshift later) but I am currently facing difficulties with the access to the server API.

Actually, when I run the image on my local machine : 
docker run -p 3000:3000 open-pryv.io:v0.1, the container runs successfully.

I am able to connect to the container send requests and get responses:

~ $ docker exec -it be4dd3879d42 bash
root@be4dd3879d42:/open-pryv.io# wget 127.0.0.1:3000
--2020-06-25 14:30:50--  http://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 150 [application/json]
Saving to: 'index.html'
[...]

But outside the container, the same call fails (directly in Windows):

~ $ wget 127.0.0.1:3000
--2020-06-25 15:33:22--  http://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

I tried to access it in many ways (changing port, investing the exposing IP, changing client) but the result is always the same.

Would you have best practices to share about it ?

------

For information, I used the following Docker file content to build my image:

FROM node:12.13.1

RUN apt-get update
RUN apt-get -y install rsync

RUN npm install -g yarn

COPY . /open-pryv.io
WORKDIR /open-pryv.io

RUN npm install -g yarn

RUN yarn setup
RUN yarn release

RUN apt-get install nano

EXPOSE 3000

CMD ["yarn", "local"]
#CMD ["yarn", "pryv"]

------

Thanks in advance for your support and kind regards,
Sébastien

**Comment by chewieplus** [comment]
NB: I forgot to mention that before compiling the Docker image, I had to call the following command to adapt the files:
**dos2unix ./babel.config.json config.json LICENSE package.json README.md**
**find components -type f -exec dos2unix {} \\;**
**find configs -type f -exec dos2unix {} \\;**
**find scripts -type f -exec dos2unix {} \\;**
**find service-mail -type f -exec dos2unix {} \\;**

to avoid issues regarding EOL in files during the execution in the Docker container.

**Comment by kebetsi** [comment]
Thanks for the notes, we have a planned dockerized Open Pryv.io release in the following days. We'll keep you posted.

**Comment by chewieplus** [comment]
Oh great ! Thanks for the info

**Comment by kebetsi** [comment]
Hi @chewieplus,

We have a first version to build or download docker images of the services https://github.com/pryv/open-pryv.io#dockerized
We'll further simplify the process in the coming days, but this may be already enough for your case.

Your feedback is welcome, have a good day!

**Comment by chewieplus** [comment]
Hi @kebetsi 

First of all, thanks a lot for your efforts. As discussed with Perki, your system is really promising and I am really proud to work with it.

Currently, I am still facing troubles with the deployment of the containers locally (on a Windows machine).

Here is my first notice, regarding the documentation (README.md).
There is a small glitch regarding the docker-compose command:
After images are built, you can simply run **`docker-compose up -f docker-compose.yml` or `docker-compose up -f docker-compose.download.yml`** instead of `sh build-local.sh` to start the containers.
instead of
After images are built, you can simply run **`docker-compose -f docker-compose.yml up` or `docker-compose -f docker-compose.download.yml up`** instead of `sh build-local.sh` to start the containers.

After this, when starting the containers using the docker-compose, I got the following results :

std@NB51167 MINGW64 /c/Projects/open-pryv.io (master)
$ sh build-local.sh docker-compose.download.yml
Assets already installed skipping
Refreshing default certificates in configs/rec.la-certificates
/c/Projects/open-pryv.io/configs/rec.la-certificates
Already up to date.
Starting open-pryvio_mongo-express_1 ... done
Starting pryv_mongo                  ... done
Recreating open_pryv_core            ... done
Recreating open_pryv_mail            ... done
**Recreating pryv_nginx                ... error**

ERROR: for pryv_nginx  Cannot start service pryv_nginx: Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

ERROR: for pryv_nginx  Cannot start service pryv_nginx: Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Encountered errors while bringing up the project.

Last tentative:
Adapt **docker-compose.yml** and **docker-compose.download.yml** 
from 
        ports:
          - 80:80

to
        ports:
          - 8080:8080

and configs/site.conf
from
# API (Core)
server {
  # redirect from http to https
  listen 80 default_server;

to
# API (Core)
server {
  # redirect from http to https
  listen 8080 default_server;

The start up acts differently but finally ends with:
**6fd826f91c18_pryv_nginx | 2020/07/06 13:58:48 [emerg] 1#1: cannot load certificate "/etc/nginx/certs/self-signed/rec.la-bundle.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/self-signed/rec.la-bundle.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)**
**6fd826f91c18_pryv_nginx | nginx: [emerg] cannot load certificate "/etc/nginx/certs/self-signed/rec.la-bundle.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certs/self-signed/rec.la-bundle.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
6fd826f91c18_pryv_nginx exited with code 1**


Have you any recommandation regarding this issue ?

Thanks a lot in advance and kind regards

**Comment by IevaNavikiene** [comment]
While running build_local.sh it had to download this repo https://github.com/pryv/rec-la.git to ./configs/rec.la-certificates/ directory. Maybe you can check if certificates exists in ./configs/rec.la-certificates/src/ directory?

**Comment by chewieplus** [comment]
Hello @IevaNavikiene

It looks like the download of the content of the https://github.com/pryv/rec-la.git repo didn't work as expected.

std@NB51167 MINGW64 /c/Projects/open-pryv.io (master)
$ ls configs/rec.la-certificates/
src/

std@NB51167 MINGW64 /c/Projects/open-pryv.io (master)
$ ls configs/rec.la-certificates/src/

leading to the same error as yesterday.
I will try to make that part manually.

Thanks for the tip ^^


-----------


After checking your script, it looks like something went wrong during a previous execution, leaving the directory empty and preventing it from either cloning it properly or refreshing it.

Now I am able to run open-pryv.io locally.

Thanks team !

**Comment by chewieplus** [comment]
Just as a side note, the difficulties I had with the MacOSX chars still occurs when I don't use the dos2unix command:

Assets already installed skipping
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Service-Mail Installed!
./setup-app-web-auth3.bash: line 2: $'\r': command not found
./setup-app-web-auth3.bash: line 4: cd: $'/app/scripts\r/..': No such file or directory
./setup-app-web-auth3.bash: line 5: $'\r': command not found
./setup-app-web-auth3.bash: line 6: $'\r': command not found
./setup-app-web-auth3.bash: line 21: syntax error near unexpected token `fi'
./setup-app-web-auth3.bash: line 21: `fi'
./setup-admin-key.bash: line 2: $'\r': command not found
./setup-admin-key.bash: line 4: cd: $'/app/scripts\r/..': No such file or directory
./setup-admin-key.bash: line 5: $'\r': command not found
./setup-admin-key.bash: line 11: syntax error near unexpected token `$'do\r''
'/setup-admin-key.bash: line 11: `for i in `seq 1 $n`; do

Setup complete!

**Comment by kebetsi** [comment]
Thanks for the explanation, @chewieplus!

I'm closing this issue.
